server.port=3000

spring.datasource.url=jdbc:mysql://localhost:3306/mydb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# =========================
# ✅ Mail Config (Gmail SMTP)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=2100030078cseh@gmail.com

# ✅ App Password WITHOUT spaces
spring.mail.password=lzudefjskvzaznxa

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# =========================
# ✅ OTP Config
# =========================
# where OTP should go (for /sendotp endpoint)
app.otp.toEmail=2100030078cseh@gmail.com

# OTP expiry seconds
app.otp.ttlSeconds=180
``